namespace Aogami.SMTV.GameData
{
    public static class SMTVItemCollection
    {
        public static readonly IReadOnlyDictionary<int, string> ItemNames = new Dictionary<int, string>()
        {
            { 0, "NOT USED:ITEM_USE_00" },
            { 1, "Life Stone" },
            { 2, "Chakra Drop" },
            { 3, "Chakra Pot" },
            { 4, "Bead" },
            { 5, "Bead Chain" },
            { 6, "Soma" },
            { 7, "Revival Bead" },
            { 8, "Balm of Life" },
            { 9, "Amrita Soda" },
            { 10, "Amrita Shower" },
            { 11, "Medicine" },
            { 12, "Ox Bezoar" },
            { 13, "Ambrosia" },
            { 14, "Muscle Drink" },
            { 15, "NOT USED:ITEM_USE_15" },
            { 16, "NOT USED:ITEM_USE_16" },
            { 17, "Fire Shard" },
            { 18, "Ice Shard" },
            { 19, "Elec Shard" },
            { 20, "Force Shard" },
            { 21, "Light Shard" },
            { 22, "Dark Shard" },
            { 23, "Fire Gem" },
            { 24, "Ice Gem" },
            { 25, "Elec Gem" },
            { 26, "Force Gem" },
            { 27, "Light Gem" },
            { 28, "Dark Gem" },
            { 29, "NOT USED:ITEM_USE_29" },
            { 30, "NOT USED:ITEM_USE_30" },
            { 31, "NOT USED:ITEM_USE_31" },
            { 32, "NOT USED:ITEM_USE_32" },
            { 33, "NOT USED:ITEM_USE_33" },
            { 34, "NOT USED:ITEM_USE_34" },
            { 35, "NOT USED:ITEM_USE_35" },
            { 36, "NOT USED:ITEM_USE_36" },
            { 37, "Poison Gem" },
            { 38, "Sleep Gem" },
            { 39, "Confusion Gem" },
            { 40, "Mirage Gem" },
            { 41, "Seal Gem" },
            { 42, "Charm Gem" },
            { 43, "Charge Gem" },
            { 44, "Concentrate Gem" },
            { 45, "Critical Gem" },
            { 46, "Spirit Drain Gem" },
            { 47, "Life Drain Gem" },
            { 48, "NOT USED:ITEM_USE_48" },
            { 49, "NOT USED:ITEM_USE_49" },
            { 50, "Purge Charm" },
            { 51, "Dispel Charm" },
            { 52, "Attack Mirror" },
            { 53, "Magic Mirror" },
            { 54, "NOT USED:ITEM_USE_54" },
            { 55, "Spyglass" },
            { 56, "NOT USED:ITEM_USE_56" },
            { 57, "NOT USED:ITEM_USE_57" },
            { 58, "NOT USED:ITEM_USE_58" },
            { 59, "NOT USED:ITEM_USE_59" },
            { 60, "Whittled Goat" },
            { 61, "Smoke Ball" },
            { 62, "Phys Dampener" },
            { 63, "Fire Dampener" },
            { 64, "Ice Dampener" },
            { 65, "Elec Dampener" },
            { 66, "Force Dampener" },
            { 67, "Light Dampener" },
            { 68, "Dark Dampener" },
            { 69, "NOT USED:ITEM_USE_69" },
            { 70, "Return Pillar" },
            { 71, "Repulse Bell" },
            { 72, "NOT USED:ITEM_USE_72" },
            { 73, "NOT USED:ITEM_USE_73" },
            { 74, "NOT USED:ITEM_USE_74" },
            { 75, "NOT USED:ITEM_USE_75" },
            { 76, "NOT USED:ITEM_USE_76" },
            { 77, "NOT USED:ITEM_USE_77" },
            { 78, "NOT USED:ITEM_USE_78" },
            { 79, "NOT USED:ITEM_USE_79" },
            { 80, "NOT USED:ITEM_USE_80" },
            { 81, "NOT USED:ITEM_USE_81" },
            { 82, "Gospel" },
            { 83, "Grimoire" },
            { 84, "Health Balm" },
            { 85, "Stamina Balm" },
            { 86, "Strength Balm" },
            { 87, "Magic Balm" },
            { 88, "Vitality Balm" },
            { 89, "Agility Balm" },
            { 90, "Luck Balm" },
            { 91, "Health Incense" },
            { 92, "Stamina Incense" },
            { 93, "Strength Incense" },
            { 94, "Magic Incense" },
            { 95, "Vitality Incense" },
            { 96, "Agility Incense" },
            { 97, "Luck Incense" },
            { 98, "Battle Sutra" },
            { 99, "Fire Sutra" },
            { 100, "Ice Sutra" },
            { 101, "Elec Sutra" },
            { 102, "Force Sutra" },
            { 103, "Light Sutra" },
            { 104, "Dark Sutra" },
            { 105, "Destruction Sutra" },
            { 106, "Healing Sutra" },
            { 107, "Aiding Sutra" },
            { 108, "Calamity Sutra" },
            { 109, "Small Glory Crystal" },
            { 110, "Large Glory Crystal" },
            { 111, "NOT USED:ITEM_USE_111" },
            { 112, "NOT USED:ITEM_USE_112" },
            { 113, "NOT USED:ITEM_USE_113" },
            { 114, "NOT USED:ITEM_USE_114" },
            { 115, "NOT USED:ITEM_USE_115" },
            { 116, "NOT USED:ITEM_USE_116" },
            { 117, "NOT USED:ITEM_USE_117" },
            { 118, "NOT USED:ITEM_USE_118" },
            { 119, "NOT USED:ITEM_USE_119" },
            { 120, "NOT USED:ITEM_USE_120" },
            { 121, "NOT USED:ITEM_USE_121" },
            { 122, "NOT USED:ITEM_USE_122" },
            { 123, "NOT USED:ITEM_USE_123" },
            { 124, "NOT USED:ITEM_USE_124" },
            { 125, "NOT USED:ITEM_USE_125" },
            { 126, "NOT USED:ITEM_USE_126" },
            { 127, "NOT USED:ITEM_USE_127" },
            { 128, "NOT USED:ITEM_USE_128" },
            { 129, "NOT USED:ITEM_USE_129" },
            { 130, "NOT USED:ITEM_USE_130" },
            { 131, "NOT USED:ITEM_USE_131" },
            { 132, "NOT USED:ITEM_USE_132" },
            { 133, "NOT USED:ITEM_USE_133" },
            { 134, "NOT USED:ITEM_USE_134" },
            { 135, "NOT USED:ITEM_USE_135" },
            { 136, "NOT USED:ITEM_USE_136" },
            { 137, "NOT USED:ITEM_USE_137" },
            { 138, "NOT USED:ITEM_USE_138" },
            { 139, "NOT USED:ITEM_USE_139" },
            { 140, "NOT USED:ITEM_USE_140" },
            { 141, "NOT USED:ITEM_USE_141" },
            { 142, "NOT USED:ITEM_USE_142" },
            { 143, "NOT USED:ITEM_USE_143" },
            { 144, "NOT USED:ITEM_USE_144" },
            { 145, "NOT USED:ITEM_USE_145" },
            { 146, "NOT USED:ITEM_USE_146" },
            { 147, "NOT USED:ITEM_USE_147" },
            { 148, "NOT USED:ITEM_USE_148" },
            { 149, "NOT USED:ITEM_USE_149" },
            { 150, "NOT USED:ITEM_USE_150" },
            { 151, "NOT USED:ITEM_USE_151" },
            { 152, "NOT USED:ITEM_USE_152" },
            { 153, "NOT USED:ITEM_USE_153" },
            { 154, "NOT USED:ITEM_USE_154" },
            { 155, "NOT USED:ITEM_USE_155" },
            { 156, "NOT USED:ITEM_USE_156" },
            { 157, "NOT USED:ITEM_USE_157" },
            { 158, "NOT USED:ITEM_USE_158" },
            { 159, "NOT USED:ITEM_USE_159" },
            { 160, "NOT USED:ITEM_USE_160" },
            { 161, "NOT USED:ITEM_USE_161" },
            { 162, "NOT USED:ITEM_USE_162" },
            { 163, "NOT USED:ITEM_USE_163" },
            { 164, "NOT USED:ITEM_USE_164" },
            { 165, "NOT USED:ITEM_USE_165" },
            { 166, "NOT USED:ITEM_USE_166" },
            { 167, "NOT USED:ITEM_USE_167" },
            { 168, "NOT USED:ITEM_USE_168" },
            { 169, "NOT USED:ITEM_USE_169" },
            { 170, "NOT USED:ITEM_USE_170" },
            { 171, "NOT USED:ITEM_USE_171" },
            { 172, "NOT USED:ITEM_USE_172" },
            { 173, "NOT USED:ITEM_USE_173" },
            { 174, "NOT USED:ITEM_USE_174" },
            { 175, "NOT USED:ITEM_USE_175" },
            { 176, "NOT USED:ITEM_USE_176" },
            { 177, "NOT USED:ITEM_USE_177" },
            { 178, "NOT USED:ITEM_USE_178" },
            { 179, "NOT USED:ITEM_USE_179" },
            { 180, "NOT USED:ITEM_USE_180" },
            { 181, "NOT USED:ITEM_USE_181" },
            { 182, "NOT USED:ITEM_USE_182" },
            { 183, "NOT USED:ITEM_USE_183" },
            { 184, "NOT USED:ITEM_USE_184" },
            { 185, "NOT USED:ITEM_USE_185" },
            { 186, "NOT USED:ITEM_USE_186" },
            { 187, "NOT USED:ITEM_USE_187" },
            { 188, "NOT USED:ITEM_USE_188" },
            { 189, "NOT USED:ITEM_USE_189" },
            { 190, "NOT USED:ITEM_USE_190" },
            { 191, "NOT USED:ITEM_USE_191" },
            { 192, "NOT USED:ITEM_USE_192" },
            { 193, "NOT USED:ITEM_USE_193" },
            { 194, "NOT USED:ITEM_USE_194" },
            { 195, "NOT USED:ITEM_USE_195" },
            { 196, "NOT USED:ITEM_USE_196" },
            { 197, "NOT USED:ITEM_USE_197" },
            { 198, "NOT USED:ITEM_USE_198" },
            { 199, "NOT USED:ITEM_USE_199" },
            { 200, "NOT USED:ITEM_USE_200" },
            { 201, "NOT USED:ITEM_USE_201" },
            { 202, "NOT USED:ITEM_USE_202" },
            { 203, "NOT USED:ITEM_USE_203" },
            { 204, "NOT USED:ITEM_USE_204" },
            { 205, "NOT USED:ITEM_USE_205" },
            { 206, "NOT USED:ITEM_USE_206" },
            { 207, "NOT USED:ITEM_USE_207" },
            { 208, "NOT USED:ITEM_USE_208" },
            { 209, "NOT USED:ITEM_USE_209" },
            { 210, "NOT USED:ITEM_USE_210" },
            { 211, "NOT USED:ITEM_USE_211" },
            { 212, "NOT USED:ITEM_USE_212" },
            { 213, "NOT USED:ITEM_USE_213" },
            { 214, "NOT USED:ITEM_USE_214" },
            { 215, "NOT USED:ITEM_USE_215" },
            { 216, "NOT USED:ITEM_USE_216" },
            { 217, "NOT USED:ITEM_USE_217" },
            { 218, "NOT USED:ITEM_USE_218" },
            { 219, "NOT USED:ITEM_USE_219" },
            { 220, "NOT USED:ITEM_USE_220" },
            { 221, "NOT USED:ITEM_SKILLGET_1" },
            { 222, "NOT USED:ITEM_SKILLGET_2" },
            { 223, "NOT USED:ITEM_SKILLGET_3" },
            { 224, "NOT USED:ITEM_SKILLGET_4" },
            { 225, "NOT USED:ITEM_SKILLGET_5" },
            { 226, "NOT USED:ITEM_SKILLGET_6" },
            { 227, "NOT USED:ITEM_SKILLGET_7" },
            { 228, "NOT USED:ITEM_SKILLGET_8" },
            { 229, "NOT USED:ITEM_SKILLGET_9" },
            { 230, "NOT USED:ITEM_SKILLGET_10" },
            { 231, "NOT USED:ITEM_SKILLGET_11" },
            { 232, "NOT USED:ITEM_SKILLGET_12" },
            { 233, "NOT USED:ITEM_SKILLGET_13" },
            { 234, "NOT USED:ITEM_SKILLGET_14" },
            { 235, "NOT USED:ITEM_SKILLGET_15" },
            { 236, "NOT USED:ITEM_SKILLGET_16" },
            { 237, "NOT USED:ITEM_SKILLGET_17" },
            { 238, "NOT USED:ITEM_SKILLGET_18" },
            { 239, "NOT USED:ITEM_SKILLGET_19" },
            { 240, "NOT USED:ITEM_SKILLGET_20" },
            { 241, "NOT USED:ITEM_SKILLGET_21" },
            { 242, "NOT USED:ITEM_SKILLGET_22" },
            { 243, "NOT USED:ITEM_SKILLGET_23" },
            { 244, "NOT USED:ITEM_SKILLGET_24" },
            { 245, "NOT USED:ITEM_SKILLGET_25" },
            { 246, "NOT USED:ITEM_SKILLGET_26" },
            { 247, "NOT USED:ITEM_SKILLGET_27" },
            { 248, "NOT USED:ITEM_SKILLGET_28" },
            { 249, "NOT USED:ITEM_SKILLGET_29" },
            { 250, "NOT USED:ITEM_SKILLGET_30" },
            { 251, "NOT USED:ITEM_SKILLGET_31" },
            { 252, "NOT USED:ITEM_SKILLGET_32" },
            { 253, "NOT USED:ITEM_SKILLGET_33" },
            { 254, "NOT USED:ITEM_SKILLGET_34" },
            { 255, "NOT USED:ITEM_SKILLGET_35" },
            { 256, "NOT USED:ITEM_SKILLGET_36" },
            { 257, "NOT USED:ITEM_SKILLGET_37" },
            { 258, "NOT USED:ITEM_SKILLGET_38" },
            { 259, "NOT USED:ITEM_SKILLGET_39" },
            { 260, "NOT USED:ITEM_SKILLGET_40" },
            { 261, "NOT USED:ITEM_SKILLGET_41" },
            { 262, "NOT USED:ITEM_SKILLGET_42" },
            { 263, "NOT USED:ITEM_SKILLGET_43" },
            { 264, "NOT USED:ITEM_SKILLGET_44" },
            { 265, "NOT USED:ITEM_SKILLGET_45" },
            { 266, "NOT USED:ITEM_SKILLGET_46" },
            { 267, "NOT USED:ITEM_SKILLGET_47" },
            { 268, "NOT USED:ITEM_SKILLGET_48" },
            { 269, "NOT USED:ITEM_SKILLGET_49" },
            { 270, "NOT USED:ITEM_SKILLGET_50" },
            { 271, "NOT USED:ITEM_SKILLGET_51" },
            { 272, "NOT USED:ITEM_SKILLGET_52" },
            { 273, "NOT USED:ITEM_SKILLGET_53" },
            { 274, "NOT USED:ITEM_SKILLGET_54" },
            { 275, "NOT USED:ITEM_SKILLGET_55" },
            { 276, "NOT USED:ITEM_SKILLGET_56" },
            { 277, "NOT USED:ITEM_SKILLGET_57" },
            { 278, "NOT USED:ITEM_SKILLGET_58" },
            { 279, "NOT USED:ITEM_SKILLGET_59" },
            { 280, "NOT USED:ITEM_SKILLGET_60" },
            { 281, "NOT USED:ITEM_SKILLGET_61" },
            { 282, "NOT USED:ITEM_SKILLGET_62" },
            { 283, "NOT USED:ITEM_SKILLGET_63" },
            { 284, "NOT USED:ITEM_SKILLGET_64" },
            { 285, "NOT USED:ITEM_SKILLGET_65" },
            { 286, "NOT USED:ITEM_SKILLGET_66" },
            { 287, "NOT USED:ITEM_SKILLGET_67" },
            { 288, "NOT USED:ITEM_SKILLGET_68" },
            { 289, "NOT USED:ITEM_SKILLGET_69" },
            { 290, "NOT USED:ITEM_SKILLGET_70" },
            { 291, "NOT USED:ITEM_SKILLGET_71" },
            { 292, "NOT USED:ITEM_SKILLGET_72" },
            { 293, "NOT USED:ITEM_SKILLGET_73" },
            { 294, "NOT USED:ITEM_SKILLGET_74" },
            { 295, "NOT USED:ITEM_SKILLGET_75" },
            { 296, "NOT USED:ITEM_SKILLGET_76" },
            { 297, "NOT USED:ITEM_SKILLGET_77" },
            { 298, "NOT USED:ITEM_SKILLGET_78" },
            { 299, "NOT USED:ITEM_SKILLGET_79" },
            { 300, "NOT USED:ITEM_SKILLGET_80" },
            { 301, "NOT USED:ITEM_SKILLGET_81" },
            { 302, "NOT USED:ITEM_SKILLGET_82" },
            { 303, "NOT USED:ITEM_SKILLGET_83" },
            { 304, "NOT USED:ITEM_SKILLGET_84" },
            { 305, "NOT USED:ITEM_SKILLGET_85" },
            { 306, "NOT USED:ITEM_SKILLGET_86" },
            { 307, "NOT USED:ITEM_SKILLGET_87" },
            { 308, "NOT USED:ITEM_SKILLGET_88" },
            { 309, "NOT USED:ITEM_SKILLGET_89" },
            { 310, "NOT USED:ITEM_SKILLGET_90" },
            { 311, "Khonsu's Essence" },
            { 312, "Zeus's Essence" },
            { 313, "Odin's Essence" },
            { 314, "Mitra's Essence" },
            { 315, "Atavaka's Essence" },
            { 316, "Horus's Essence" },
            { 317, "Thoth's Essence" },
            { 318, "Khonsu Ra's Essence" },
            { 319, "Vishnu's Essence" },
            { 320, "Baal's Essence" },
            { 321, "Demeter's Essence" },
            { 322, "Anahita's Essence" },
            { 323, "Lakshmi's Essence" },
            { 324, "Norn's Essence" },
            { 325, "Idun's Essence" },
            { 326, "Sarasvati's Essence" },
            { 327, "Ishtar's Essence" },
            { 328, "Scathach's Essence" },
            { 329, "Parvati's Essence" },
            { 330, "Ame-no-Uzume's Essence" },
            { 331, "Fortuna's Essence" },
            { 332, "Maria's Essence" },
            { 333, "Artemis's Essence" },
            { 334, "Hanuman's Essence" },
            { 335, "Fionn's Essence" },
            { 336, "Cu Chulainn's Essence" },
            { 337, "Kurama Tengu's Essence" },
            { 338, "Amanozako's Essence" },
            { 339, "Koppa Tengu's Essence" },
            { 340, "Apsaras's Essence" },
            { 341, "Agathion's Essence" },
            { 342, "Mandrake's Essence" },
            { 343, "Titania's Essence" },
            { 344, "Oberon's Essence" },
            { 345, "Silky's Essence" },
            { 346, "Setanta's Essence" },
            { 347, "Kelpie's Essence" },
            { 348, "High Pixie's Essence" },
            { 349, "Jack-o-Lantern's Essence" },
            { 350, "Jack Frost's Essence" },
            { 351, "Pixie's Essence" },
            { 352, "Queen Medb's Essence" },
            { 353, "Succubus's Essence" },
            { 354, "Kaiwan's Essence" },
            { 355, "Lilim's Essence" },
            { 356, "Incubus's Essence" },
            { 357, "Mokoi's Essence" },
            { 358, "Sandman's Essence" },
            { 359, "Lilith's Essence" },
            { 360, "Black Frost's Essence" },
            { 361, "Nuwa's Essence" },
            { 362, "Amon's Essence" },
            { 363, "Mara's Essence" },
            { 364, "Mephisto's Essence" },
            { 365, "Chi You's Essence" },
            { 366, "Surt's Essence" },
            { 367, "Beelzebub's Essence" },
            { 368, "Arioch's Essence" },
            { 369, "Belial's Essence" },
            { 370, "Abaddon's Essence" },
            { 371, "Moloch's Essence" },
            { 372, "Belphegor's Essence" },
            { 373, "King Frost's Essence" },
            { 374, "Mithras's Essence" },
            { 375, "Loki's Essence" },
            { 376, "Huang Long's Essence" },
            { 377, "Quetzalcoatl's Essence" },
            { 378, "Qing Long's Essence" },
            { 379, "Xuanwu's Essence" },
            { 380, "Ananta's Essence" },
            { 381, "Yamata-no-Orochi's Essence" },
            { 382, "Naga Raja's Essence" },
            { 383, "Yurlungur's Essence" },
            { 384, "Naga's Essence" },
            { 385, "Vasuki's Essence" },
            { 386, "Seth's Essence" },
            { 387, "Basilisk's Essence" },
            { 388, "Aitvaras's Essence" },
            { 389, "Hydra's Essence" },
            { 390, "Fafnir's Essence" },
            { 391, "Barong's Essence" },
            { 392, "Anubis's Essence" },
            { 393, "Makami's Essence" },
            { 394, "Baihu's Essence" },
            { 395, "Chimera's Essence" },
            { 396, "Cironnup's Essence" },
            { 397, "Shiisaa's Essence" },
            { 398, "Cerberus's Essence" },
            { 399, "Orthrus's Essence" },
            { 400, "Loup-garou's Essence" },
            { 401, "Nekomata's Essence" },
            { 402, "Inugami's Essence" },
            { 403, "Orobas's Essence" },
            { 404, "Cait Sith's Essence" },
            { 405, "Bugs's Essence" },
            { 406, "Nue's Essence" },
            { 407, "Bicorn's Essence" },
            { 408, "Mothman's Essence" },
            { 409, "Hayataro's Essence" },
            { 410, "Flaemis's Essence" },
            { 411, "Aquans's Essence" },
            { 412, "Aeros's Essence" },
            { 413, "Erthys's Essence" },
            { 414, "NOT USED:ITEM_UTSUSEMI_104" },
            { 415, "NOT USED:ITEM_UTSUSEMI_105" },
            { 416, "NOT USED:ITEM_UTSUSEMI_106" },
            { 417, "NOT USED:ITEM_UTSUSEMI_107" },
            { 418, "Black Ooze's Essence" },
            { 419, "Legion's Essence" },
            { 420, "Slime's Essence" },
            { 421, "Shiva's Essence" },
            { 422, "Mot's Essence" },
            { 423, "Zaou-Gongen's Essence" },
            { 424, "Asura's Essence" },
            { 425, "Chernobog's Essence" },
            { 426, "Dionysus's Essence" },
            { 427, "Danu's Essence" },
            { 428, "Inanna's Essence" },
            { 429, "Kali's Essence" },
            { 430, "Cybele's Essence" },
            { 431, "Skadi's Essence" },
            { 432, "Isis's Essence" },
            { 433, "Kikuri-Hime's Essence" },
            { 434, "Hariti's Essence" },
            { 435, "Nuwa's Essence" },
            { 436, "Alilat's Essence" },
            { 437, "Thor's Essence" },
            { 438, "Futsunushi's Essence" },
            { 439, "Attis's Essence" },
            { 440, "Bishamonten's Essence" },
            { 441, "Jikokuten's Essence" },
            { 442, "Koumokuten's Essence" },
            { 443, "Zouchouten's Essence" },
            { 444, "Arahabaki's Essence" },
            { 445, "Oyamatsumi's Essence" },
            { 446, "Kushinada-Hime's Essence" },
            { 447, "Sukuna-Hikona's Essence" },
            { 448, "Okuninushi's Essence" },
            { 449, "Take-Minakata's Essence" },
            { 450, "Ganesha's Essence" },
            { 451, "Siegfried's Essence" },
            { 452, "Valkyrie's Essence" },
            { 453, "Yoshitsune's Essence" },
            { 454, "Neko Shogun's Essence" },
            { 455, "Mada's Essence" },
            { 456, "Girimekhala's Essence" },
            { 457, "Pazuzu's Essence" },
            { 458, "Mishaguji's Essence" },
            { 459, "Baphomet's Essence" },
            { 460, "Lahmu's Essence" },
            { 461, "Abdiel's Essence" },
            { 462, "Metatron's Essence" },
            { 463, "Michael's Essence" },
            { 464, "Gabriel's Essence" },
            { 465, "Sraosha's Essence" },
            { 466, "Raphael's Essence" },
            { 467, "Sandalphon's Essence" },
            { 468, "Uriel's Essence" },
            { 469, "Camael's Essence" },
            { 470, "Melchizedek's Essence" },
            { 471, "Throne's Essence" },
            { 472, "Dominion's Essence" },
            { 473, "Power's Essence" },
            { 474, "Principality's Essence" },
            { 475, "Archangel's Essence" },
            { 476, "Angel's Essence" },
            { 477, "Abdiel's Essence" },
            { 478, "Adramelech's Essence" },
            { 479, "Flauros's Essence" },
            { 480, "Nebiros's Essence" },
            { 481, "Berith's Essence" },
            { 482, "Ose's Essence" },
            { 483, "Eligor's Essence" },
            { 484, "Forneus's Essence" },
            { 485, "Andras's Essence" },
            { 486, "Decarabia's Essence" },
            { 487, "Garuda's Essence" },
            { 488, "Zhuque's Essence" },
            { 489, "Yatagarasu's Essence" },
            { 490, "Jatayu's Essence" },
            { 491, "Feng Huang's Essence" },
            { 492, "Thunderbird's Essence" },
            { 493, "Anzu's Essence" },
            { 494, "Zhen's Essence" },
            { 495, "Muu Shuwuu's Essence" },
            { 496, "Onmoraki's Essence" },
            { 497, "Cleopatra's Essence" },
            { 498, "Rangda's Essence" },
            { 499, "Dakini's Essence" },
            { 500, "Atropos's Essence" },
            { 501, "Yakshini's Essence" },
            { 502, "Lachesis's Essence" },
            { 503, "Clotho's Essence" },
            { 504, "Manananggal's Essence" },
            { 505, "Lamia's Essence" },
            { 506, "Mermaid's Essence" },
            { 507, "Leanan Sidhe's Essence" },
            { 508, "Ongyo-Ki's Essence" },
            { 509, "Shiki-Ouji's Essence" },
            { 510, "Sui-Ki's Essence" },
            { 511, "Fuu-Ki's Essence" },
            { 512, "Kin-Ki's Essence" },
            { 513, "Azumi's Essence" },
            { 514, "Ippon-Datara's Essence" },
            { 515, "Daemon's Essence" },
            { 516, "Oni's Essence" },
            { 517, "Hecatoncheires's Essence" },
            { 518, "Loa's Essence" },
            { 519, "Rakshasa's Essence" },
            { 520, "Turdak's Essence" },
            { 521, "Macabre's Essence" },
            { 522, "Kaya-no-Hime's Essence" },
            { 523, "Tsuchigumo's Essence" },
            { 524, "Narcissus's Essence" },
            { 525, "Hua Po's Essence" },
            { 526, "Koropokkur's Essence" },
            { 527, "Sudama's Essence" },
            { 528, "Kodama's Essence" },
            { 529, "Pisaca's Essence" },
            { 530, "Kumbhanda's Essence" },
            { 531, "Poltergeist's Essence" },
            { 532, "Obariyon's Essence" },
            { 533, "Preta's Essence" },
            { 534, "Trumpeter's Essence" },
            { 535, "Mother Harlot's Essence" },
            { 536, "Black Rider's Essence" },
            { 537, "Red Rider's Essence" },
            { 538, "White Rider's Essence" },
            { 539, "Alice's Essence" },
            { 540, "Hell Biker's Essence" },
            { 541, "Daisoujou's Essence" },
            { 542, "Pale Rider's Essence" },
            { 543, "Matador's Essence" },
            { 544, "Aogami Type-1 Essence" },
            { 545, "Aogami Type-2 Essence" },
            { 546, "Aogami Type-3 Essence" },
            { 547, "Aogami Type-4 Essence" },
            { 548, "Aogami Type-5 Essence" },
            { 549, "Aogami Type-6 Essence" },
            { 550, "Aogami Type-7 Essence" },
            { 551, "Aogami Type-8 Essence" },
            { 552, "Aogami Type-9 Essence" },
            { 553, "Aogami Type-10 Essence" },
            { 554, "Aogami Type-0 Essence" },
            { 555, "Demi-fiend's Essence" },
            { 556, "NOT USED:ITEM_UTSUSEMI_246" },
            { 557, "NOT USED:ITEM_UTSUSEMI_247" },
            { 558, "NOT USED:ITEM_UTSUSEMI_248" },
            { 559, "NOT USED:ITEM_UTSUSEMI_249" },
            { 560, "NOT USED:ITEM_UTSUSEMI_250" },
            { 561, "NOT USED:ITEM_UTSUSEMI_251" },
            { 562, "NOT USED:ITEM_UTSUSEMI_252" },
            { 563, "NOT USED:ITEM_UTSUSEMI_253" },
            { 564, "NOT USED:ITEM_UTSUSEMI_254" },
            { 565, "NOT USED:ITEM_UTSUSEMI_255" },
            { 566, "NOT USED:ITEM_UTSUSEMI_256" },
            { 567, "NOT USED:ITEM_UTSUSEMI_257" },
            { 568, "NOT USED:ITEM_UTSUSEMI_258" },
            { 569, "NOT USED:ITEM_UTSUSEMI_259" },
            { 570, "NOT USED:ITEM_UTSUSEMI_260" },
            { 571, "NOT USED:ITEM_UTSUSEMI_261" },
            { 572, "NOT USED:ITEM_UTSUSEMI_262" },
            { 573, "NOT USED:ITEM_UTSUSEMI_263" },
            { 574, "NOT USED:ITEM_UTSUSEMI_264" },
            { 575, "NOT USED:ITEM_UTSUSEMI_265" },
            { 576, "NOT USED:ITEM_UTSUSEMI_266" },
            { 577, "NOT USED:ITEM_UTSUSEMI_267" },
            { 578, "NOT USED:ITEM_UTSUSEMI_268" },
            { 579, "NOT USED:ITEM_UTSUSEMI_269" },
            { 580, "NOT USED:ITEM_UTSUSEMI_270" },
            { 581, "NOT USED:ITEM_UTSUSEMI_271" },
            { 582, "NOT USED:ITEM_UTSUSEMI_272" },
            { 583, "NOT USED:ITEM_UTSUSEMI_273" },
            { 584, "NOT USED:ITEM_UTSUSEMI_274" },
            { 585, "NOT USED:ITEM_UTSUSEMI_275" },
            { 586, "NOT USED:ITEM_UTSUSEMI_276" },
            { 587, "NOT USED:ITEM_UTSUSEMI_277" },
            { 588, "NOT USED:ITEM_UTSUSEMI_278" },
            { 589, "NOT USED:ITEM_UTSUSEMI_279" },
            { 590, "NOT USED:ITEM_UTSUSEMI_280" },
            { 591, "NOT USED:ITEM_UTSUSEMI_281" },
            { 592, "NOT USED:ITEM_UTSUSEMI_282" },
            { 593, "NOT USED:ITEM_UTSUSEMI_283" },
            { 594, "NOT USED:ITEM_UTSUSEMI_284" },
            { 595, "NOT USED:ITEM_UTSUSEMI_285" },
            { 596, "NOT USED:ITEM_UTSUSEMI_286" },
            { 597, "NOT USED:ITEM_UTSUSEMI_287" },
            { 598, "NOT USED:ITEM_UTSUSEMI_288" },
            { 599, "NOT USED:ITEM_UTSUSEMI_289" },
            { 600, "NOT USED:ITEM_UTSUSEMI_290" },
            { 601, "NOT USED:ITEM_UTSUSEMI_291" },
            { 602, "NOT USED:ITEM_UTSUSEMI_292" },
            { 603, "NOT USED:ITEM_UTSUSEMI_293" },
            { 604, "NOT USED:ITEM_UTSUSEMI_294" },
            { 605, "NOT USED:ITEM_UTSUSEMI_295" },
            { 606, "NOT USED:ITEM_UTSUSEMI_296" },
            { 607, "NOT USED:ITEM_UTSUSEMI_297" },
            { 608, "NOT USED:ITEM_UTSUSEMI_298" },
            { 609, "NOT USED:ITEM_UTSUSEMI_299" },
            { 610, "NOT USED:ITEM_UTSUSEMI_300" },
            { 611, "NOT USED:ITEM_UTSUSEMI_301" },
            { 612, "NOT USED:ITEM_UTSUSEMI_302" },
            { 613, "NOT USED:ITEM_UTSUSEMI_303" },
            { 614, "NOT USED:ITEM_UTSUSEMI_304" },
            { 615, "NOT USED:ITEM_UTSUSEMI_305" },
            { 616, "Fortune" },
            { 617, "Soda" },
            { 618, "Melted Doll" },
            { 619, "Cloth Mask" },
            { 620, "Cartridge Game Console" },
            { 621, "Shabby Building Material" },
            { 622, "Hexagram Trading Card" },
            { 623, "Can of Jelly" },
            { 624, "Anime Paperweight" },
            { 625, "Simple Undershirt" },
            { 626, "Segata III Game Console" },
            { 627, "Mouse Mummy" },
            { 628, "Telephone Card" },
            { 629, "Can of Oden" },
            { 630, "Electronic Music Box" },
            { 631, "School Swimsuit" },
            { 632, "Tablet Game Console" },
            { 633, "Crow Mummy" },
            { 634, "Hologram Trading Card" },
            { 635, "Time Capsule" },
            { 636, "Balloon Value Pack" },
            { 637, "Antique Shirt" },
            { 638, "Game Console with Handle" },
            { 639, "Mysterious Mummy" },
            { 640, "Black Tape Set" },
            { 641, "Ripped Manga" },
            { 642, "High-Capacity Bottle" },
            { 643, "Vinyl Umbrella" },
            { 644, "Powder Box" },
            { 645, "Bottle Container" },
            { 646, "Radio-yaki" },
            { 647, "Rubber Duck" },
            { 648, "Old Newspaper" },
            { 649, "Old Magazine" },
            { 650, "Novel" },
            { 651, "Sealed Magazine" },
            { 652, "Cardboard Cap Bottle" },
            { 653, "Marble Bottle" },
            { 654, "Maid Costume" },
            { 655, "Golden Triangle" },
            { 656, "Golden Apple" },
            { 657, "Akiha-Gongen Talisman" },
            { 658, "Key of Austerity" },
            { 659, "Key of Benevolence" },
            { 660, "Key of Harmony" },
            { 661, "NOT USED:ITEM_IMPORTANT_006" },
            { 662, "NOT USED:ITEM_IMPORTANT_007" },
            { 663, "NOT USED:ITEM_IMPORTANT_008" },
            { 664, "NOT USED:ITEM_IMPORTANT_009" },
            { 665, "NOT USED:ITEM_IMPORTANT_010" },
            { 666, "NOT USED:ITEM_IMPORTANT_011" },
            { 667, "NOT USED:ITEM_IMPORTANT_012" },
            { 668, "NOT USED:ITEM_IMPORTANT_013" },
            { 669, "NOT USED:ITEM_IMPORTANT_014" },
            { 670, "NOT USED:ITEM_IMPORTANT_015" },
            { 671, "NOT USED:ITEM_IMPORTANT_016" },
            { 672, "NOT USED:ITEM_IMPORTANT_017" },
            { 673, "NOT USED:ITEM_IMPORTANT_018" },
            { 674, "NOT USED:ITEM_IMPORTANT_019" },
            { 675, "NOT USED:ITEM_IMPORTANT_020" },
            { 676, "NOT USED:ITEM_IMPORTANT_021" },
            { 677, "NOT USED:ITEM_IMPORTANT_022" },
            { 678, "NOT USED:ITEM_IMPORTANT_023" },
            { 679, "NOT USED:ITEM_IMPORTANT_024" },
            { 680, "NOT USED:ITEM_IMPORTANT_025" },
            { 681, "NOT USED:ITEM_IMPORTANT_026" },
            { 682, "NOT USED:ITEM_IMPORTANT_027" },
            { 683, "NOT USED:ITEM_IMPORTANT_028" },
            { 684, "NOT USED:ITEM_IMPORTANT_029" },
            { 685, "NOT USED:ITEM_IMPORTANT_030" },
            { 686, "NOT USED:ITEM_IMPORTANT_031" },
            { 687, "NOT USED:ITEM_IMPORTANT_032" },
            { 688, "NOT USED:ITEM_IMPORTANT_033" },
            { 689, "NOT USED:ITEM_IMPORTANT_034" },
            { 690, "NOT USED:ITEM_IMPORTANT_035" },
            { 691, "NOT USED:ITEM_IMPORTANT_036" },
            { 692, "NOT USED:ITEM_IMPORTANT_037" },
            { 693, "NOT USED:ITEM_IMPORTANT_038" },
            { 694, "NOT USED:ITEM_IMPORTANT_039" },
            { 695, "NOT USED:ITEM_IMPORTANT_040" },
            { 696, "NOT USED:ITEM_IMPORTANT_041" },
            { 697, "NOT USED:ITEM_IMPORTANT_042" },
            { 698, "NOT USED:ITEM_IMPORTANT_043" },
            { 699, "NOT USED:ITEM_IMPORTANT_044" },
            { 700, "NOT USED:ITEM_IMPORTANT_045" },
            { 701, "NOT USED:ITEM_IMPORTANT_046" },
            { 702, "NOT USED:ITEM_IMPORTANT_047" },
            { 703, "NOT USED:ITEM_IMPORTANT_048" },
            { 704, "NOT USED:ITEM_IMPORTANT_049" },
            { 705, "NOT USED:ITEM_IMPORTANT_050" },
            { 706, "NOT USED:ITEM_IMPORTANT_051" },
            { 707, "NOT USED:ITEM_IMPORTANT_052" },
            { 708, "NOT USED:ITEM_IMPORTANT_053" },
            { 709, "NOT USED:ITEM_IMPORTANT_054" },
            { 710, "NOT USED:ITEM_IMPORTANT_055" },
            { 711, "NOT USED:ITEM_IMPORTANT_056" },
            { 712, "NOT USED:ITEM_IMPORTANT_057" },
            { 713, "NOT USED:ITEM_IMPORTANT_058" },
            { 714, "NOT USED:ITEM_IMPORTANT_059" },
            { 715, "NOT USED:ITEM_IMPORTANT_060" },
            { 716, "NOT USED:ITEM_IMPORTANT_061" },
            { 717, "NOT USED:ITEM_IMPORTANT_062" },
            { 718, "NOT USED:ITEM_IMPORTANT_063" },
            { 719, "NOT USED:ITEM_IMPORTANT_064" },
            { 720, "NOT USED:ITEM_IMPORTANT_065" },
            { 721, "NOT USED:ITEM_IMPORTANT_066" },
            { 722, "NOT USED:ITEM_IMPORTANT_067" },
            { 723, "NOT USED:ITEM_IMPORTANT_068" },
            { 724, "NOT USED:ITEM_IMPORTANT_069" },
            { 725, "NOT USED:ITEM_IMPORTANT_070" },
            { 726, "NOT USED:ITEM_IMPORTANT_071" },
            { 727, "NOT USED:ITEM_IMPORTANT_072" },
            { 728, "NOT USED:ITEM_IMPORTANT_073" },
            { 729, "NOT USED:ITEM_IMPORTANT_074" },
            { 730, "NOT USED:ITEM_IMPORTANT_075" },
            { 731, "NOT USED:ITEM_IMPORTANT_076" },
            { 732, "NOT USED:ITEM_IMPORTANT_077" },
            { 733, "NOT USED:ITEM_IMPORTANT_078" },
            { 734, "NOT USED:ITEM_IMPORTANT_079" },
            { 735, "NOT USED:ITEM_IMPORTANT_080" },
            { 736, "NOT USED:ITEM_IMPORTANT_081" },
            { 737, "NOT USED:ITEM_IMPORTANT_082" },
            { 738, "NOT USED:ITEM_IMPORTANT_083" },
            { 739, "NOT USED:ITEM_IMPORTANT_084" },
            { 740, "NOT USED:ITEM_IMPORTANT_085" },
            { 741, "NOT USED:ITEM_IMPORTANT_086" },
            { 742, "NOT USED:ITEM_IMPORTANT_087" },
            { 743, "NOT USED:ITEM_IMPORTANT_088" },
            { 744, "NOT USED:ITEM_IMPORTANT_089" },
            { 745, "NOT USED:ITEM_IMPORTANT_090" },
            { 746, "NOT USED:ITEM_IMPORTANT_091" },
            { 747, "NOT USED:ITEM_IMPORTANT_092" },
            { 748, "NOT USED:ITEM_IMPORTANT_093" },
            { 749, "NOT USED:ITEM_IMPORTANT_094" },
            { 750, "NOT USED:ITEM_IMPORTANT_095" },
            { 751, "NOT USED:ITEM_IMPORTANT_096" },
            { 752, "NOT USED:ITEM_IMPORTANT_097" },
            { 753, "NOT USED:ITEM_IMPORTANT_098" },
            { 754, "NOT USED:ITEM_IMPORTANT_099" },
            { 755, "NOT USED:ITEM_IMPORTANT_100" },
            { 756, "Jatayu Egg" },
            { 757, "Mandrake Root" },
            { 758, "Giant Bird's Feather" },
            { 759, "Shikigami Talisman" },
            { 760, "Mothman Capture Pot" },
            { 761, "Kumbhanda's Bottle" },
            { 762, "Incubus's Letter" },
            { 763, "Frozen King Salmon" },
            { 764, "Kunitsu Keystone" },
            { 765, "Gibbon Guitar" },
            { 766, "Large Model Kit" },
            { 767, "TV-Game Combination" },
            { 768, "Horn of Plenty" },
            { 769, "Diamond" },
            { 770, "Garnet" },
            { 771, "Aquamarine" },
            { 772, "Dragon Scale" },
            { 773, "Girimekhala's Head" },
            { 774, "Lord's Sword" },
            { 775, "Winged Sun Crest" },
            { 776, "Angel Ring" },
            { 777, "Seed of Life" },
            { 778, "Inugami Head" },
            { 779, "Bicorn Horn" },
            { 780, "Horus's Head" },
            { 781, "Dark Contract" },
            { 782, "Magnetite Powder" },
            { 783, "Menorah of Knowledge" },
            { 784, "Menorah of Foundation" },
            { 785, "Menorah of Eternity" },
            { 786, "Menorah of Dignity" },
            { 787, "Menorah of Compassion" },
            { 788, "Menorah of Insight" },
            { 789, "Menorah of Wisdom" },
            { 790, "Menorah of Majesty" },
            { 791, "Menorah of Beauty" },
            { 792, "Menorah of Glory" },
            { 793, "Menorah of Sovereignty" },
            { 794, "Student Handbook" },
            { 795, "Sake and Dango Medley" },
            { 796, "Fiendish Sash" },
            { 797, "NOT USED:ITEM_IMPORTANT_142" },
            { 798, "NOT USED:ITEM_IMPORTANT_143" },
            { 799, "NOT USED:ITEM_IMPORTANT_144" },
            { 800, "NOT USED:ITEM_IMPORTANT_145" },
            { 801, "NOT USED:ITEM_IMPORTANT_146" },
            { 802, "NOT USED:ITEM_IMPORTANT_147" },
            { 803, "NOT USED:ITEM_IMPORTANT_148" },
            { 804, "NOT USED:ITEM_IMPORTANT_149" },
            { 805, "NOT USED:ITEM_IMPORTANT_150" },
            { 806, "Haunt Talisman" },
            { 807, "Raptor Talisman" },
            { 808, "Herald Talisman" },
            { 809, "Megami Talisman" },
            { 810, "Avian Talisman" },
            { 811, "Divine Talisman" },
            { 812, "Yoma Talisman" },
            { 813, "Vile Talisman" },
            { 814, "Deity Talisman" },
            { 815, "Wargod Talisman" },
            { 816, "Avatar Talisman" },
            { 817, "Holy Talisman" },
            { 818, "Genma Talisman" },
            { 819, "Element Talisman" },
            { 820, "Fairy Talisman" },
            { 821, "Beast Talisman" },
            { 822, "Jirae Talisman" },
            { 823, "Fiend Talisman" },
            { 824, "Jaki Talisman" },
            { 825, "Wilder Talisman" },
            { 826, "Fury Talisman" },
            { 827, "Lady Talisman" },
            { 828, "Dragon Talisman" },
            { 829, "Kishin Talisman" },
            { 830, "Kunitsu Talisman" },
            { 831, "Femme Talisman" },
            { 832, "Brute Talisman" },
            { 833, "Fallen Talisman" },
            { 834, "Night Talisman" },
            { 835, "Snake Talisman" },
            { 836, "Tyrant Talisman" },
            { 837, "Drake Talisman" },
            { 838, "Foul Talisman" },
            { 839, "NOT USED:ITEM_IMPORTANT_184" },
            { 840, "NOT USED:ITEM_IMPORTANT_185" },
            { 841, "NOT USED:ITEM_IMPORTANT_186" },
            { 842, "NOT USED:ITEM_IMPORTANT_187" },
            { 843, "NOT USED:ITEM_IMPORTANT_188" },
            { 844, "NOT USED:ITEM_IMPORTANT_189" },
            { 845, "NOT USED:ITEM_IMPORTANT_190" },
            { 846, "NOT USED:ITEM_IMPORTANT_191" },
            { 847, "NOT USED:ITEM_IMPORTANT_192" },
            { 848, "NOT USED:ITEM_IMPORTANT_193" },
            { 849, "NOT USED:ITEM_IMPORTANT_194" },
            { 850, "NOT USED:ITEM_IMPORTANT_195" },
            { 851, "NOT USED:ITEM_IMPORTANT_196" },
            { 852, "NOT USED:ITEM_IMPORTANT_197" },
            { 853, "NOT USED:ITEM_IMPORTANT_198" },
            { 854, "NOT USED:ITEM_IMPORTANT_199" },
            { 855, "NOT USED:ITEM_IMPORTANT_200" }
        };
    }
}
