namespace Aogami.SMTV.GameData
{
    public static class SMTVMiracleCollection
    {
        public static readonly IReadOnlyDictionary<int, string> MiracleList = new Dictionary<int, string>()
        {
            { 0, "NOT USED:GP_NAME_000" },
            { 1, "Knowledge of Tools" },
            { 2, "Unyielding Will" },
            { 3, "Invigorating Defense" },
            { 4, "NOT USED:GP_NAME_004" },
            { 5, "NOT USED:GP_NAME_005" },
            { 6, "NOT USED:GP_NAME_006" },
            { 7, "NOT USED:GP_NAME_007" },
            { 8, "NOT USED:GP_NAME_008" },
            { 9, "NOT USED:GP_NAME_009" },
            { 10, "NOT USED:GP_NAME_010" },
            { 11, "Vengeance" },
            { 12, "NOT USED:GP_NAME_012" },
            { 13, "Forestall" },
            { 14, "Constant Vigilance" },
            { 15, "Embolden" },
            { 16, "Enhanced Summon" },
            { 17, "Dread" },
            { 18, "Kindred Favor" },
            { 19, "Articulate Discourse" },
            { 20, "Pacification" },
            { 21, "Inspiring Covenant" },
            { 22, "Divine Persuasion" },
            { 23, "Divine Eminence" },
            { 24, "Deathly Aura I" },
            { 25, "Deathly Aura II" },
            { 26, "Deathly Aura III" },
            { 27, "Hand of God" },
            { 28, "Warrior's Conception" },
            { 29, "Unforgotten Memories" },
            { 30, "Inheritance Violation" },
            { 31, "Rank Violation" },
            { 32, "Art of Essences I" },
            { 33, "Art of Essences II" },
            { 34, "Art of Essences III" },
            { 35, "Healer's Hospitality I" },
            { 36, "Healer's Hospitality II" },
            { 37, "Merchant's Hospitality I" },
            { 38, "Merchant's Hospitality II" },
            { 39, "Summoner's Hospitality I" },
            { 40, "Summoner's Hospitality II" },
            { 41, "Summoner's Hospitality III" },
            { 42, "Skill Manifestation" },
            { 43, "Demonic Discipline" },
            { 44, "Prayer of Strength" },
            { 45, "Prayer of Vitality" },
            { 46, "Prayer of Magic" },
            { 47, "Prayer of Agility" },
            { 48, "Prayer of Luck" },
            { 49, "Empowering Cheer I" },
            { 50, "Empowering Cheer II" },
            { 51, "Demon Proficiency I" },
            { 52, "Demon Proficiency II" },
            { 53, "Demon Proficiency III" },
            { 54, "Demon Proficiency IV" },
            { 55, "Divine Garrison I" },
            { 56, "Divine Garrison II" },
            { 57, "Divine Garrison III" },
            { 58, "Divine Garrison IV" },
            { 59, "Divine Garrison V" },
            { 60, "Divine Garrison VI" },
            { 61, "Divine Proficiency I" },
            { 62, "Divine Proficiency II" },
            { 63, "Divine Proficiency III" },
            { 64, "Divine Proficiency IV" },
            { 65, "Almighty Mastery I" },
            { 66, "Almighty Mastery II" },
            { 67, "Almighty Mastery III" },
            { 68, "Almighty Mastery IV" },
            { 69, "Almighty Mastery V" },
            { 70, "Physical Mastery I" },
            { 71, "Physical Mastery II" },
            { 72, "Physical Mastery III" },
            { 73, "Physical Mastery IV" },
            { 74, "Physical Mastery V" },
            { 75, "Fire Mastery I" },
            { 76, "Fire Mastery II" },
            { 77, "Fire Mastery III" },
            { 78, "Fire Mastery IV" },
            { 79, "Fire Mastery V" },
            { 80, "Ice Mastery I" },
            { 81, "Ice Mastery II" },
            { 82, "Ice Mastery III" },
            { 83, "Ice Mastery IV" },
            { 84, "Ice Mastery V" },
            { 85, "Electric Mastery I" },
            { 86, "Electric Mastery II" },
            { 87, "Electric Mastery III" },
            { 88, "Electric Mastery IV" },
            { 89, "Electric Mastery V" },
            { 90, "Force Mastery I" },
            { 91, "Force Mastery II" },
            { 92, "Force Mastery III" },
            { 93, "Force Mastery IV" },
            { 94, "Force Mastery V" },
            { 95, "Light Mastery I" },
            { 96, "Light Mastery II" },
            { 97, "Light Mastery III" },
            { 98, "Light Mastery IV" },
            { 99, "Light Mastery V" },
            { 100, "Dark Mastery I" },
            { 101, "Dark Mastery II" },
            { 102, "Dark Mastery III" },
            { 103, "Dark Mastery IV" },
            { 104, "Dark Mastery V" },
            { 105, "Recover Mastery I" },
            { 106, "Recover Mastery II" },
            { 107, "Recover Mastery III" },
            { 108, "Support Mastery I" },
            { 109, "Support Mastery II" },
            { 110, "Support Mastery III" },
            { 111, "Ailment Mastery I" },
            { 112, "Ailment Mastery II" },
            { 113, "Ailment Mastery III" },
            { 114, "Ailment Mastery IV" },
            { 115, "Ailment Mastery V" },
            { 116, "Art of Intervention" },
            { 117, "Divine Amalgamation" },
            { 118, "Divine Garrison VII" },
            { 119, "Divine Garrison VIII" },
            { 120, "Divine Garrison IX" },
            { 121, "Magatsuhi Wellspring" },
            { 122, "Vengeful Opportunist" },
            { 123, "Fell Swoop" },
            { 124, "Counter Incentive: Resist" },
            { 125, "Counter Incentive: Null" },
            { 126, "Race Transcendence" },
            { 127, "Magatsuhi Dispersion" },
            { 128, "NOT USED:GP_NAME_128" },
            { 129, "Skillful Conservation" }
        };
    }
}
