namespace Aogami.SMTV.GameData
{
    public static class SMTVMiracleCollection
    {
        public static readonly IReadOnlyDictionary<int, string> MiracleList = new Dictionary<int, string>()
        {
            { 0, "NOT USED:GP_NAME_000" },
            { 1, "Knowledge of Tools" },
            { 2, "Unyielding Will" },
            { 3, "Invigorating Defense" },
            { 4, "NOT USED:GP_NAME_004" },
            { 5, "NOT USED:GP_NAME_005" },
            { 6, "NOT USED:GP_NAME_006" },
            { 7, "NOT USED:GP_NAME_007" },
            { 8, "NOT USED:GP_NAME_008" },
            { 9, "NOT USED:GP_NAME_009" },
            { 10, "NOT USED:GP_NAME_010" },
            { 11, "Vengeance" },
            { 12, "NOT USED:GP_NAME_012" },
            { 13, "Forestall" },
            { 14, "Constant Vigilance" },
            { 15, "Embolden" },
            { 16, "Enhanced Summon" },
            { 17, "Dread" },
            { 18, "Kindred Favor" },
            { 19, "Articulate Discourse" },
            { 20, "Pacification" },
            { 21, "Inspiring Covenant" },
            { 22, "Divine Persuasion" },
            { 23, "Divine Eminence" },
            { 24, "Deathly Aura I" },
            { 25, "Deathly Aura II" },
            { 26, "Deathly Aura III" },
            { 27, "Hand of God" },
            { 28, "Warrior's Conception" },
            { 29, "Unforgotten Memories" },
            { 30, "Inheritance Violation" },
            { 31, "Rank Violation" },
            { 32, "Art of Essences I" },
            { 33, "Art of Essences II" },
            { 34, "Art of Essences III" },
            { 35, "Healer's Hospitality I" },
            { 36, "Healer's Hospitality II" },
            { 37, "Merchant's Hospitality I" },
            { 38, "Merchant's Hospitality II" },
            { 39, "Summoner's Hospitality I" },
            { 40, "Summoner's Hospitality II" },
            { 41, "Summoner's Hospitality III" },
            { 42, "Skill Manifestation" },
            { 43, "Demonic Discipline" },
            { 44, "Prayer of Strength" },
            { 45, "Prayer of Vitality" },
            { 46, "Prayer of Magic" },
            { 47, "Prayer of Agility" },
            { 48, "Prayer of Luck" },
            { 49, "Empowering Cheer I" },
            { 50, "Empowering Cheer II" },
            { 51, "Demon Proficiency I" },
            { 52, "Demon Proficiency II" },
            { 53, "Demon Proficiency III" },
            { 54, "Demon Proficiency IV" },
            { 55, "Divine Garrison I" },
            { 56, "Divine Garrison II" },
            { 57, "Divine Garrison III" },
            { 58, "Divine Garrison IV" },
            { 59, "Divine Garrison V" },
            { 60, "Divine Garrison VI" },
            { 61, "Divine Proficiency I" },
            { 62, "Divine Proficiency II" },
            { 63, "Divine Proficiency III" },
            { 64, "Divine Proficiency IV" },
            { 65, "Almighty Mastery I" },
            { 66, "Almighty Mastery II" },
            { 67, "Almighty Mastery III" },
            { 68, "Almighty Mastery IV" },
            { 69, "Almighty Mastery V" },
            { 70, "Physical Mastery I" },
            { 71, "Physical Mastery II" },
            { 72, "Physical Mastery III" },
            { 73, "Physical Mastery IV" },
            { 74, "Physical Mastery V" },
            { 75, "Fire Mastery I" },
            { 76, "Fire Mastery II" },
            { 77, "Fire Mastery III" },
            { 78, "Fire Mastery IV" },
            { 79, "Fire Mastery V" },
            { 80, "Ice Mastery I" },
            { 81, "Ice Mastery II" },
            { 82, "Ice Mastery III" },
            { 83, "Ice Mastery IV" },
            { 84, "Ice Mastery V" },
            { 85, "Electric Mastery I" },
            { 86, "Electric Mastery II" },
            { 87, "Electric Mastery III" },
            { 88, "Electric Mastery IV" },
            { 89, "Electric Mastery V" },
            { 90, "Force Mastery I" },
            { 91, "Force Mastery II" },
            { 92, "Force Mastery III" },
            { 93, "Force Mastery IV" },
            { 94, "Force Mastery V" },
            { 95, "Light Mastery I" },
            { 96, "Light Mastery II" },
            { 97, "Light Mastery III" },
            { 98, "Light Mastery IV" },
            { 99, "Light Mastery V" },
            { 100, "Dark Mastery I" },
            { 101, "Dark Mastery II" },
            { 102, "Dark Mastery III" },
            { 103, "Dark Mastery IV" },
            { 104, "Dark Mastery V" },
            { 105, "Recover Mastery I" },
            { 106, "Recover Mastery II" },
            { 107, "Recover Mastery III" },
            { 108, "Support Mastery I" },
            { 109, "Support Mastery II" },
            { 110, "Support Mastery III" },
            { 111, "Ailment Mastery I" },
            { 112, "Ailment Mastery II" },
            { 113, "Ailment Mastery III" },
            { 114, "Ailment Mastery IV" },
            { 115, "Ailment Mastery V" },
            { 116, "Art of Intervention" },
            { 117, "Divine Amalgamation" },
            { 118, "Divine Garrison VII" },
            { 119, "Divine Garrison VIII" },
            { 120, "Divine Garrison IX" },
            { 121, "Magatsuhi Wellspring" },
            { 122, "Vengeful Opportunist" },
            { 123, "Fell Swoop" },
            { 124, "Counter Incentive: Resist" },
            { 125, "Counter Incentive: Null" },
            { 126, "Race Transcendence" },
            { 127, "Magatsuhi Dispersion" },
            { 128, "NOT USED:GP_NAME_128" },
            { 129, "Skillful Conservation" }
        };

        public static readonly IReadOnlyDictionary<int, string> MiracleListHelp = new Dictionary<int, string>()
        {
            { 0, "NOT USED:GP_HM_000" },
            { 1, "Allows your demons to use items during battle." },
            { 2, "When a guarding ally is attacked, the Magatsuhi Gauge increases a little." },
            { 3, "An ally's MP will recover when guarding." },
            { 4, "NOT USED:GP_HM_004" },
            { 5, "NOT USED:GP_HM_005" },
            { 6, "NOT USED:GP_HM_006" },
            { 7, "NOT USED:GP_HM_007" },
            { 8, "NOT USED:GP_HM_008" },
            { 9, "NOT USED:GP_HM_009" },
            { 10, "NOT USED:GP_HM_010" },
            { 11, "The Magatsuhi Gauge greatly increases anytime an ally dies." },
            { 12, "NOT USED:GP_HM_012" },
            { 13, "Slashing an enemy in the field without being noticed will greatly increase the Magatsuhi Gauge at the start of a battle." },
            { 14, "The Magatsuhi Gauge increases a little at the start of a battle." },
            { 15, "Raises the amount added to Magatsuhi Gauge each turn." },
            { 16, "Demon allies summoned in battle will have a random stat raised by 1 rank." },
            { 17, "All enemies will have a random stat lowered by 1 rank at the start of a battle." },
            { 18, "Talking with a demon while having that same demon in your party will prompt them to occasionally heal you in battle." },
            { 19, "Talking with a demon uses 1/2 of a Press Turn Icon." },
            { 20, "If a demon's mood sours mid-negotiation, they may forgive you." },
            { 21, "Recruiting demons in battle will cause them to immediately level up." },
            { 22, "Demons will sometimes join you unconditionally." },
            { 23, "Demons above the Nahobino's level can be recruited through negotiation." },
            { 24, "Cornered demons may beg for their lives." },
            { 25, "Demand Macca from cornered demons." },
            { 26, "Demand Essence from cornered demons." },
            { 27, "Rare chance to acquire one extra relic." },
            { 28, "Newly-fused demons will gain a stat bonus based on the stats of the demons fused." },
            { 29, "Newly fused demons will gain EXP based on the stats of the demons fused." },
            { 30, "A demon's starting skills can be overwritten during skill inheritance." },
            { 31, "Level limitation for demon fusion is lifted." },
            { 32, "Allows an additional skill to be selected from essences." },
            { 33, "Allows up to two additional skills to be selected from essences." },
            { 34, "Unlocks all essence skills." },
            { 35, "The healing cost at leyline founts is reduced by 25%." },
            { 36, "The healing cost at leyline founts is reduced by 50%." },
            { 37, "Item prices at the Cadaver's Hollow are reduced by 25%." },
            { 38, "Item prices at the Cadaver's Hollow are reduced by 50%." },
            { 39, "The cost of summoning demons from the Demon Compendium is reduced by 10%." },
            { 40, "The cost of summoning demons from the Demon Compendium is reduced by 30%." },
            { 41, "The cost of summoning demons from the Demon Compendium is reduced by 50%." },
            { 42, "A demon ally may awaken to a new skill when leveling up." },
            { 43, "Increases the amount of EXP earned by demons in your stock after a battle." },
            { 44, "Additional +1 increase to a demon ally's Strength when the demon levels up (Only applies up to a certain level)." },
            { 45, "Additional +1 increase to a demon ally's Vitality when the demon levels up (Only applies up to a certain level)." },
            { 46, "Additional +1 increase to a demon ally's Magic when the demon levels up (Only applies up to a certain level)." },
            { 47, "Additional +1 increase to a demon ally's Agility when the demon levels up (Only applies up to a certain level)." },
            { 48, "Additional +1 increase to a demon ally's Luck when the demon levels up (Only applies up to a certain level)." },
            { 49, "Half of MAX HP and MP are recovered when leveling up." },
            { 50, "HP and MP are fully recovered when leveling up." },
            { 51, "Increases demon ally's skill slots by 1." },
            { 52, "Increases demon ally's skill slots by 1." },
            { 53, "Increases demon ally's skill slots by 1." },
            { 54, "Increases demon ally's skill slots by 1." },
            { 55, "Increases demon stock by 1." },
            { 56, "Increases demon stock by 1." },
            { 57, "Increases demon stock by 2." },
            { 58, "Increases demon stock by 2." },
            { 59, "Increases demon stock by 2." },
            { 60, "Increases demon stock by 2." },
            { 61, "Increases the Nahobino's skill slots by 1." },
            { 62, "Increases the Nahobino's skill slots by 1." },
            { 63, "Increases the Nahobino's skill slots by 1." },
            { 64, "Increases the Nahobino's skill slots by 1." },
            { 65, "Increases the Nahobino's Almighty skill potential by 1." },
            { 66, "Increases the Nahobino's Almighty skill potential by 2." },
            { 67, "Increases the Nahobino's Almighty skill potential by 2." },
            { 68, "Increases the Nahobino's Almighty skill potential by 2." },
            { 69, "Increases the Nahobino's Almighty skill potential by 2." },
            { 70, "Increases the Nahobino's Physical skill potential by 1." },
            { 71, "Increases the Nahobino's Physical skill potential by 2." },
            { 72, "Increases the Nahobino's Physical skill potential by 2." },
            { 73, "Increases the Nahobino's Physical skill potential by 2." },
            { 74, "Increases the Nahobino's Physical skill potential by 2." },
            { 75, "Increases the Nahobino's Fire skill potential by 1." },
            { 76, "Increases the Nahobino's Fire skill potential by 2." },
            { 77, "Increases the Nahobino's Fire skill potential by 2." },
            { 78, "Increases the Nahobino's Fire skill potential by 2." },
            { 79, "Increases the Nahobino's Fire skill potential by 2." },
            { 80, "Increases the Nahobino's Ice skill potential by 1." },
            { 81, "Increases the Nahobino's Ice skill potential by 2." },
            { 82, "Increases the Nahobino's Ice skill potential by 2." },
            { 83, "Increases the Nahobino's Ice skill potential by 2." },
            { 84, "Increases the Nahobino's Ice skill potential by 2." },
            { 85, "Increases the Nahobino's Electric skill potential by 1." },
            { 86, "Increases the Nahobino's Electric skill potential by 2." },
            { 87, "Increases the Nahobino's Electric skill potential by 2." },
            { 88, "Increases the Nahobino's Electric skill potential by 2." },
            { 89, "Increases the Nahobino's Electric skill potential by 2." },
            { 90, "Increases the Nahobino's Force skill potential by 1." },
            { 91, "Increases the Nahobino's Force skill potential by 2." },
            { 92, "Increases the Nahobino's Force skill potential by 2." },
            { 93, "Increases the Nahobino's Force skill potential by 2." },
            { 94, "Increases the Nahobino's Force skill potential by 2." },
            { 95, "Increases the Nahobino's Light skill potential by 1." },
            { 96, "Increases the Nahobino's Light skill potential by 2." },
            { 97, "Increases the Nahobino's Light skill potential by 2." },
            { 98, "Increases the Nahobino's Light skill potential by 2." },
            { 99, "Increases the Nahobino's Light skill potential by 2." },
            { 100, "Increases the Nahobino's Dark skill potential by 1." },
            { 101, "Increases the Nahobino's Dark skill potential by 2." },
            { 102, "Increases the Nahobino's Dark skill potential by 2." },
            { 103, "Increases the Nahobino's Dark skill potential by 2." },
            { 104, "Increases the Nahobino's Dark skill potential by 2." },
            { 105, "Increases the Nahobino's Healing skill potential by 1." },
            { 106, "Increases the Nahobino's Healing skill potential by 2." },
            { 107, "Increases the Nahobino's Healing skill potential by 2." },
            { 108, "Increases the Nahobino's Support skill potential by 1." },
            { 109, "Increases the Nahobino's Support skill potential by 2." },
            { 110, "Increases the Nahobino's Support skill potential by 2." },
            { 111, "Increases the Nahobino's Ailment skill potential by 1." },
            { 112, "Increases the Nahobino's Ailment skill potential by 2." },
            { 113, "Increases the Nahobino's Ailment skill potential by 2." },
            { 114, "Increases the Nahobino's Ailment skill potential by 2." },
            { 115, "Increases the Nahobino's Ailment skill potential by 2." },
            { 116, "Use a demon ally's action to speak with a demon." },
            { 117, "Allows the Nahobino to acquire affinity resistances from essences during Essence Fusion." },
            { 118, "Increases demon stock by 2." },
            { 119, "Increases demon stock by 3." },
            { 120, "Increases demon stock by 3." },
            { 121, "All allies will slightly recover HP and MP if the Magatsuhi Gauge is full at the start of a turn." },
            { 122, "The Magatsuhi Gauge will slightly increase when guarding." },
            { 123, "The Magatsuhi Gauge will very slightly increase when inflicting WEAK or CRITICAL." },
            { 124, "The Magatsuhi Gauge will slightly increase when an ally's affinity resistance reduces damage from an enemy attack." },
            { 125, "The Magatsuhi Gauge will increase when an ally Nulls, Drains, or Repels an enemy attack." },
            { 126, "The Nahobino will become able to use race-specific Magatsuhi Skills held by other party members." },
            { 127, "The enemy Omagatoki: Critical effect will end when an ally guards, evades, Nulls, Repels, or Drains an enemy attack." },
            { 128, "NOT USED:GP_HM_128" },
            { 129, "Very slightly decreases the amount of Magatsuhi consumed when using Magatsuhi Skills." }
        };
    }
}
